version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    executor:
      name: windows/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "root/backend/backend_api/backend_api/backend_api.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci.nuget\packages
          key: dotnet-packages-v1-{{ checksum "root/backend/backend_api/backend_api/backend_api.csproj" }}
      - run:
          name: "Run Application Tests"
          command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test