
# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:

  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            export CONN_STRING=`echo $CONN_STRING`
            dotnet build
  ##################### USER TESTS ##################### 
  User:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet build
  User_UnitTests:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet test --filter EditProfileUnitTests
            dotnet test --filter ViewProfileUnitTests
  User_IntegrationTests:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet test --filter AuthServiceTest
  ##################### USER TESTS ##################### 

  ################ NOTIFICATION TESTS ################## 
  Notification:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet build
  UnitTest_Notification:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet test --filter CreateNotificationTests
            dotnet test --filter RetrieveNotificationsTests
  IntegrationTests_Notification:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet test --filter NotificationServiceTests
  ################ NOTIFICATION TESTS ################

  ################ NOTICEBOARD TESTS ################# 
  Noticeboard:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet build

  UnitTests_NoticeBoard:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet test --filter CreateNoticeBoardThreadTests
            dotnet test --filter DeleteNoticeBoardThreadTests
            dotnet test --filter RetrieveNoticeBoardThreadTests
            
  IntegrationTests_NoticeBoard:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet test --filter NoticeBoardService
  ################ NOTICEBOARD TESTS ################

  ################# FORUM TESTS #####################
  Forum:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet build

  IntegrationTests_Forum:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet test --filter ForumServiceTest
################# FORUM TESTS #################

############### BOOKING TESTS ##################
  Booking:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet build

  IntegrationTests_Booking:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          working_directory: ~/project/backend/backend_api.Tests
          name: Run tests
          command: |
            dotnet test --filter BookingServiceTests
################# BOOKING TESTS ##############

################# BOOKING TESTS ##############

################# WORKFLOW ################### 
workflows:
  Rabbitania Testing:
    jobs:
      - build
      - User:
          requires:
            - build
      - Notification:
          requires:
            - build
      - Noticeboard:
          requires:
            - build
      - Forum:
          requires:
            - build
      - Booking:
          requires:
            - build
    
      - User_UnitTests:
          requires:
            - User
      - User_IntegrationTests:
          requires:
            - User
      - UnitTests_NoticeBoard:
          requires:
            - Noticeboard
      - IntegrationTests_NoticeBoard:
          requires:
            - Noticeboard
      - UnitTest_Notification:
          requires:
            - Notification
      - IntegrationTests_Notification:
          requires:
            - Notification
      - IntegrationTests_Forum:
          requires:
            - Forum
      - IntegrationTests_Booking:
          requires:
            - Booking
            

     
      































