// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_api.Data.Booking;

namespace backend_api.Data.Migrations
{
    [DbContext(typeof(BookingScheduleContext))]
    [Migration("20210802083208_UpdateBookingKeyMigration")]
    partial class UpdateBookingKeyMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "6.0.0-preview.4.21253.1")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("backend_api.Models.Booking.BookingSchedule", b =>
                {
                    b.Property<int>("Office")
                        .HasColumnType("integer");

                    b.Property<string>("TimeSlot")
                        .HasColumnType("text");

                    b.Property<int>("Availability")
                        .HasColumnType("integer");

                    b.HasKey("Office", "TimeSlot");

                    b.ToTable("BookingSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
