// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_api.Data.NoticeBoard;

namespace backend_api.Data.Migrations
{
    [DbContext(typeof(NoticeBoardContext))]
    [Migration("20210705085733_InitialNoticeBoardCreate")]
    partial class InitialNoticeBoardCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "6.0.0-preview.4.21253.1")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("backend_api.Models.NoticeBoard.NoticeBoard", b =>
                {
                    b.Property<int>("ThreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MinLevel")
                        .HasColumnType("integer");

                    b.Property<int>("PermittedUserRoles")
                        .HasColumnType("integer");

                    b.Property<string>("ThreadContent")
                        .HasColumnType("text");

                    b.Property<string>("ThreadTitle")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ThreadId");

                    b.ToTable("NoticeBoard");
                });
#pragma warning restore 612, 618
        }
    }
}
