// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend_api.Data.NoticeBoard;

namespace backend_api.Data.Migrations
{
    [DbContext(typeof(NoticeBoardContext))]
    partial class NoticeBoardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "6.0.0-preview.4.21253.1")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("backend_api.Models.NoticeBoard.NoticeBoard", b =>
                {
                    b.Property<int>("ThreadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Icon1")
                        .HasColumnType("integer");

                    b.Property<int>("Icon2")
                        .HasColumnType("integer");

                    b.Property<int>("Icon3")
                        .HasColumnType("integer");

                    b.Property<int>("Icon4")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("MinEmployeeLevel")
                        .HasColumnType("integer");

                    b.Property<int>("PermittedUserRoles")
                        .HasColumnType("integer");

                    b.Property<string>("ThreadContent")
                        .HasColumnType("text");

                    b.Property<string>("ThreadTitle")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ThreadId");

                    b.HasIndex("UserId");

                    b.ToTable("NoticeBoard");
                });

            modelBuilder.Entity("backend_api.Models.NoticeBoard.NoticeBoard", b =>
                {
                    b.HasOne("backend_api.Models.User.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
